# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

CriticOpinion.delete_all
Movie.delete_all
Critic.delete_all
UserOpinion.delete_all
User.delete_all

User.create!(name: "Dustin")

Movie.create!(title: "Iron Man 3", year: 2013, description: "Marvel\'s \"Iron Man 3\" pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy\'s hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man? (c) Disney", rt_id: 771217285, image_url: "http://content8.flixster.com/movie/11/17/05/11170594_det.jpg")
Movie.create!(title: "Oz the Great and Powerful", year: 2013, description: "Disney\'s fantastical adventure \"Oz The Great and Powerful,\" directed by Sam Raimi, imagines the origins of L. Frank Baum\'s beloved wizard character. When Oscar Diggs (James Franco), a small-time circus magician with dubious ethics, is hurled away from dusty Kansas to the vibrant Land of Oz, he thinks he\'s hit the jackpot-fame and fortune are his for the taking-that is until he meets three witches, Theodora (Mila Kunis), Evanora (Rachel Weisz) and Glinda (Michelle Williams), who are not convinced he is the great wizard everyone\'s been expecting. Reluctantly drawn into the epic problems facing the Land of Oz and its inhabitants, Oscar must find out who is good and who is evil before it is too late. Putting his magical arts to use through illusion, ingenuity-and even a bit of wizardry-Oscar transforms himself not only into the great wizard but into a better man as well. When small-time magician Oscar Diggs (James Franco) pulls one flimflam too many, he finds himself hurled into the fantastical Land of Oz where he must somehow transform himself into the great wizard-and just maybe into a better man as well. -- (C) Walt Disney", rt_id: 771211175, image_url: "http://content7.flixster.com/movie/11/16/82/11168213_det.jpg")
Movie.create!(title: "Fast & Furious 6", year: 2013, description: "Vin Diesel, Paul Walker and Dwayne Johnson lead the returning cast of all-stars as the global blockbuster franchise built on speed races to its next continent in Fast & Furious 6. Reuniting for their most high-stakes adventure yet, fan favorites Jordana Brewster, Michelle Rodriguez, Tyrese Gibson, Sung Kang, Gal Gadot, Chris \"Ludacris\" Bridges and Elsa Pataky are joined by badass series newcomers Luke Evans and Gina Carano. Since Dom (Diesel) and Brian\'s (Walker) Rio heist toppled a kingpin\'s empire and left their crew with $100 million, our heroes have scattered across the globe. But their inability to return home and living forever on the lam have left their lives incomplete. Meanwhile, Hobbs (Johnson) has been tracking an organization of lethally skilled mercenary drivers across 12 countries, whose mastermind (Evans) is aided by a ruthless second-in-command revealed to be the love Dom thought was dead, Letty (Rodriguez). The only way to stop the criminal outfit is to outmatch them at street level, so Hobbs asks Dom to assemble his elite team in London. Payment? Full pardons for all of them so they can return home and make their families whole again. Building on the worldwide blockbuster success of Fast Five and taking the action, stunts and narrative to even greater heights, Fast & Furious 6 sees director Justin Lin back behind the camera for the fourth time. He is supported by longtime producers Neal H. Moritz and Vin Diesel, who welcome producer Clayton Townsend back to the series. (c) Fox", rt_id: 771246668, image_url: "http://content8.flixster.com/movie/11/16/92/11169222_det.jpg")
Movie.create!(title: "Star Trek Into Darkness", year: 2013, description: "In Summer 2013, pioneering director J.J. Abrams will deliver an explosive action thriller that takes \'Star Trek Into Darkness.\' When the crew of the Enterprise is called back home, they find an unstoppable force of terror from within their own organization has detonated the fleet and everything it stands for, leaving our world in a state of crisis. With a personal score to settle, Captain Kirk leads a manhunt to a war-zone world to capture a one man weapon of mass destruction. As our heroes are propelled into an epic chess game of life and death, love will be challenged, friendships will be torn apart, and sacrifices must be made for the only family Kirk has left: his crew. (c) Paramount", rt_id: 771190753, image_url: "http://content7.flixster.com/movie/11/17/12/11171241_det.jpg")
Movie.create!(title: "The Croods", year: 2012, description: "The Croods tells the story of the world\'s first family road trip. When their cave is destroyed, the Crood family must embark on a comedy adventure into strange and spectacular territory in search of a new home. As if patriarch Grug (Cage) didn\'t already have enough to handle, it goes from bad to worse when they encounter an imaginative nomad named Guy (Reynolds.) With Guy\'s help the Croods conquer their fear of the outside world and discover that they have exactly what it takes to survive - each other.(c) Paramount", rt_id: 770818015, image_url: "http://content8.flixster.com/movie/11/17/04/11170438_det.jpg")
Movie.create!(title: "Man of Steel", year: 2013, description: "A young boy learns that he has extraordinary powers and is not of this Earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind. -- (C) Warner Bros", rt_id: 770678819, image_url: "http://content6.flixster.com/movie/11/17/13/11171304_det.jpg")
Movie.create!(title: "The Great Gatsby", year: 2013, description: "\"The Great Gatsby\" follows Fitzgerald-like, would-be writer Nick Carraway (Tobey Maguire) as he leaves the Midwest and comes to New York City in the spring of 1922, an era of loosening morals, glittering jazz, bootleg kings, and sky-rocketing stocks. Chasing his own American Dream, Nick lands next door to a mysterious, party-giving millionaire, Jay Gatsby (Leonardo DiCaprio), and across the bay from his cousin, Daisy (Carey Mulligan), and her philandering, blue-blooded husband, Tom Buchanan (Joel Edgerton). It is thus that Nick is drawn into the captivating world of the super rich, their illusions, loves and deceits. As Nick bears witness, within and without of the world he inhabits, he pens a tale of impossible love, incorruptible dreams and high-octane tragedy, and holds a mirror to our own modern times and struggles. -- (C) WB", rt_id: 771240552, image_url: "http://content7.flixster.com/movie/11/17/12/11171265_det.jpg")
Movie.create!(title: "Identity Thief", year: 2013, description: "Unlimited funds have allowed Diana (McCarthy) to live it up on the outskirts of Miami, where the queen of retail buys whatever strikes her fancy. There\'s only one glitch: The ID she\'s using to finance these sprees reads \"Sandy Bigelow Patterson\"....and it belongs to an accounts rep (Bateman) who lives halfway across the U.S. With only one week to hunt down the con artist before his world implodes, the real Sandy Bigelow Patterson heads south to confront the woman with an all-access pass to his life. And as he attempts to bribe, coax and wrangle her the 2,000 miles to Denver, one easy target will discover just how tough it is to get your name back. -- (C) Official Site", rt_id: 771270981, image_url: "http://content6.flixster.com/movie/11/17/09/11170920_det.jpg")
Movie.create!(title: "G.I. Joe: Retaliation", year: 2013, description: "In this sequel, the G.I. Joes are not only fighting their mortal enemy Cobra; they are forced to contend with threats from within the government that jeopardize their very existence. -- (C) Paramount", rt_id: 771241227, image_url: "http://content7.flixster.com/movie/11/17/18/11171817_det.jpg")
Movie.create!(title: "The Hangover Part III", year: 2013, description: "\"The Hangover Part III\" is the third and final film in director Todd Phillips\' record-shattering comedy franchise. This time, there\'s no wedding. No bachelor party. What could go wrong, right? But when the Wolfpack hits the road, all bets are off. (c) WB", rt_id: 771268395, image_url: "http://content8.flixster.com/movie/11/17/08/11170890_det.jpg")
Movie.create!(title: "Olympus Has Fallen", year: 2013, description: "When the White House (Secret Service Code: \"Olympus\") is captured by a terrorist mastermind and the President is kidnapped, disgraced former Presidential guard Mike Banning finds himself trapped within the building. As our national security team scrambles to respond, they are forced to rely on Banning\'s inside knowledge to help retake the White House, save the President and avert an even bigger crisis. Antoine Fuqua (Training Day) directs an all-star cast featuring Gerard Butler, Aaron Eckhart, Morgan Freeman, Angela Bassett, Melissa Leo, Ashley Judd and Rick Yune. (c) FilmDistrict", rt_id: 771320125, image_url: "http://content6.flixster.com/movie/11/16/99/11169984_det.png")
Movie.create!(title: "Epic", year: 2013, description: "EPIC is a 3D CG adventure comedy that reveals a fantastical world unlike any other. From the creators of ICE AGE and RIO, EPIC tells the story of an ongoing battle between the forces of good, who keep the natural world alive, and the forces of evil, who wish to destroy it. When a teenage girl finds herself magically transported into this secret universe, she teams up with an elite band of warriors and a crew of comical, larger-than-life figures, to save their world...and ours. -- (C) Fox", rt_id: 771249677, image_url: "http://content7.flixster.com/movie/11/17/15/11171541_det.jpg")
Movie.create!(title: "42", year: 2013, description: "Hero is a word we hear often in sports, but heroism is not always about achievements on the field of play. \"42\" tells the story of two men-the great Jackie Robinson and legendary Brooklyn Dodgers GM Branch Rickey-whose brave stand against prejudice forever changed the world by changing the game of baseball. In 1946, Branch Rickey (Harrison Ford) put himself at the forefront of history when he signed Jackie Robinson (Chadwick Boseman) to the team, breaking Major League Baseball\'s infamous color line. But the deal also put both Robinson and Rickey in the firing line of the public, the press and even other players. Facing unabashed racism from every side, Robinson was forced to demonstrate tremendous courage and restraint by not reacting in kind, knowing that any incident could destroy his and Rickey\'s hopes. Instead, Number 42 let his talent on the field do the talking-ultimately winning over fans and his teammates, silencing his critics, and paving the way for others to follow. (c) WB", rt_id: 771305747, image_url: "http://content8.flixster.com/movie/11/17/18/11171806_det.jpg")
Movie.create!(title: "Oblivion", year: 2013, description: "Tom Cruise stars in Oblivion, an original and groundbreaking cinematic event from the visionary director of TRON: Legacy and producers of Rise of the Planet of the Apes. On a spectacular future Earth that has evolved beyond recognition, one man\'s confrontation with the past will lead him on a journey of redemption and discovery as he battles to save mankind. 2077: Jack Harper (Cruise) serves as a security repairmen stationed on an evacuated Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying alien threat who still scavenges what\'s left of our planet, Jack\'s mission is almost complete. In a matter of two weeks, he will join the remaining survivors on a lunar colony far from the war-torn world he has long called home. Living in and patrolling the breathtaking skies from thousands of feet above, Jack\'s soaring existence is brought crashing down after he rescues a beautiful stranger from a downed spacecraft. Drawn to Jack through a connection that transcends logic, her arrival triggers a chain of events that forces him to question everything he thought he knew. With a reality that is shattered as he discovers shocking truths that connect him to Earth of the past, Jack will be pushed to a heroism he didn\'t know he contained within. The fate of humanity now rests solely in the hands of a man who believed our world was soon to be lost forever. (c)Universal", rt_id: 771245728, image_url: "http://content9.flixster.com/movie/11/17/08/11170839_det.jpg")
Movie.create!(title: "Now You See Me", year: 2013, description: "NOW YOU SEE ME pits an elite FBI squad in a game of cat and mouse against \"The Four Horsemen\", a super-team of the world\'s greatest illusionists. \"The Four Horsemen\" pull off a series of daring heists against corrupt business leaders during their performances, showering the stolen profits on their audiences while staying one step ahead of the law. (c) Summit/Lionsgate", rt_id: 771245005, image_url: "http://content6.flixster.com/movie/11/17/04/11170496_det.jpg")
Movie.create!(title: "Baby Mama", year: 2008, description: "", rt_id: 770681823, image_url: "http://content8.flixster.com/movie/10/87/33/10873378_det.jpg")
Movie.create!(title: "Safe Haven", year: 2013, description: "An affirming and suspenseful story about a young woman\'s struggle to love again, Safe Haven is based on the novel from Nicholas Sparks, the best-selling author behind the hit films The Notebook and Dear John. When a mysterious young woman arrives in a small North Carolina town, her reluctance to join the tight knit community raises questions about her past. Slowly, she begins putting down roots, and gains the courage to start a relationship with Alex, a widowed store owner with two young children. But dark secrets intrude on her new life with such terror that she is forced to rediscover the meaning of sacrifice and rely on the power of love in this deeply moving romantic thriller.", rt_id: 770893918, image_url: "http://content7.flixster.com/movie/11/16/77/11167789_det.jpg")
Movie.create!(title: "A Good Day To Die Hard", year: 2013, description: "John McClane (Bruce Willis) heads to Russia in this fifth installment of the Die Hard film series. Skip Woods (The A-Team) provides the script, with Max Payne\'s John Moore directing. ~ Jeremy Wheeler, Rovi", rt_id: 771257607, image_url: "http://content8.flixster.com/movie/11/17/12/11171258_det.jpg")
Movie.create!(title: "Warm Bodies", year: 2013, description: "A funny new twist on a classic love story, WARM BODIES is a poignant tale about the power of human connection. After a zombie epidemic, R (a highly unusual zombie) encounters Julie (a human survivor), and rescues her from a zombie attack. Julie sees that R is different from the other zombies, and as the two form a special relationship in their struggle for survival, R becomes increasingly more human - setting off an exciting, romantic, and often comical chain of events that begins to transform the other zombies and maybe even the whole lifeless world. (c) Summit", rt_id: 771238285, image_url: "http://content8.flixster.com/movie/11/17/14/11171434_det.jpg")
Movie.create!(title: "Jack the Giant Slayer", year: 2013, description: "\"Jack the Giant Slayer\" tells the story of an ancient war that is reignited when a young farmhand unwittingly opens a gateway between our world and a fearsome race of giants. Unleashed on the Earth for the first time in centuries, the giants strive to reclaim the land they once lost, forcing the young man, Jack (Nicholas Hoult) into the battle of his life to stop them. Fighting for a kingdom, its people, and the love of a brave princess, he comes face to face with the unstoppable warriors he thought only existed in legend-and gets the chance to become a legend himself.-- (C) Warner Bros", rt_id: 771189410, image_url: "http://content8.flixster.com/movie/11/16/98/11169862_det.jpg")
c = Critic.create!(name: "Anthony Lane", publication: "New Yorker")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "false", url: "http://www.newyorker.com/arts/reviews/film/iron_man_3_black", critic: c, movie: m)
c = Critic.create!(name: "Christopher Orr", publication: "The Atlantic")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "true", url: "http://www.theatlantic.com/entertainment/archive/2013/05/-i-iron-man-3-i-the-liberation-of-tony-stark/275524/", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "false", url: "http://www.denverpost.com/movies/ci_23151454/downey-cracks-wise-but-iron-man-3-shows", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0503/Iron-Man-3-is-all-action-match-ups?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "Vulture")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "true", url: "http://www.vulture.com/2013/05/movie-review-iron-man-3.html", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/iron-man-3-a-fresh-twist-to-the-package-of-wisecracks-and-spectacle/article11684636/", critic: c, movie: m)
c = Critic.create!(name: "Rene Rodriguez", publication: "Miami Herald")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "true", url: "http://www.miami.com/039iron-man-3039-pg-13-article", critic: c, movie: m)
c = Critic.create!(name: "Kenneth Turan", publication: "Los Angeles Times")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "true", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-mn-iron-man-3-review-20130503,0,1671494.story", critic: c, movie: m)
c = Critic.create!(name: "Bob Mondello", publication: "NPR")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "true", url: "http://www.npr.org/2013/05/02/180621158/in-iron-man-3-a-metalhead-gets-the-blues?ft=1&f=1045&utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Ann Hornaday", publication: "Washington Post")
m = Movie.find_by_rt_id(771217285)
CriticOpinion.create!(like: "false", url: "http://www.washingtonpost.com/gog/movies/iron-man-3,1175591/critic-review.html#reviewNum1", critic: c, movie: m)
c = Critic.create!(name: "James Berardinelli", publication: "ReelViews")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "true", url: "http://www.reelviews.net/php_review_template.php?identifier=2592", critic: c, movie: m)
c = Critic.create!(name: "Randy Myers", publication: "San Jose Mercury News")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "false", url: "http://www.mercurynews.com/breaking-news/ci_22731528/review-oz-great-and-powerful-follows-blockbuster-road", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "New York Magazine")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "false", url: "http://www.vulture.com/2013/03/movie-review-oz-the-great-and-powerful.html", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "true", url: "http://www.denverpost.com/movies/ci_22733035/movie-review-oz-great-and-powerful-more-amusing", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "true", url: "http://www.cnn.com/2013/03/08/showbiz/movies/oz-great-powerful-review/index.html?iref=allsearch", critic: c, movie: m)
c = Critic.create!(name: "Chris Vognar", publication: "Dallas Morning News")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "false", url: "http://www.dallasnews.com/entertainment/movies/reviews/20130307-oz-the-great-and-powerful-places-noise-and-spectacle-above-charm-d.ece", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0308/Oz-The-Great-and-Powerful-is-less-than-magical?nav=397-csm_subcategory-topStories", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130307/OPINION03/303070302/1034/ent02/Review-Sumptuous-Oz-Great-Powerful-salutes-classic", critic: c, movie: m)
c = Critic.create!(name: "Joe Williams", publication: "St. Louis Post-Dispatch")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "false", url: "http://www.stltoday.com/entertainment/movies/reviews/oz-prequel-is-pretty-but-lacks-heart-brains-and-courage/article_0ffb3420-d635-5c57-9adb-2546c74770c0.html", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771211175)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/oz-the-great-and-powerful-a-big-budget-misfire-thats-the-very-opposite-of-magic/article9479230/", critic: c, movie: m)
c = Critic.create!(name: "Anthony Lane", publication: "New Yorker")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.newyorker.com/arts/reviews/film/fast_furious_6_lin", critic: c, movie: m)
c = Critic.create!(name: "James Berardinelli", publication: "ReelViews")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "false", url: "http://www.reelviews.net/php_review_template.php?identifier=2622&utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.denverpost.com/movies/ci_23302034/movie-review-vin-diesel-and-paul-walker-return", critic: c, movie: m)
c = Critic.create!(name: "Joe Williams", publication: "St. Louis Post-Dispatch")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "false", url: "http://www.stltoday.com/entertainment/movies/joe-williams/fast-furious-puts-mindlessness-into-overdrive/article_e0eee4b2-0580-543b-8021-558eafef9b72.html?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.cnn.com/2013/05/24/showbiz/movies/fast-furious-review-charity/index.html?iref=allsearch", critic: c, movie: m)
c = Critic.create!(name: "Ian Buckwalter", publication: "The Atlantic")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.theatlantic.com/entertainment/archive/2013/05/surprising-things-happen-when-you-watch-6-i-fast-and-furious-i-films-in-a-row/276203/", critic: c, movie: m)
c = Critic.create!(name: "Tom Russo", publication: "Boston Globe")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.boston.com/ae/movies/2013/05/23/still-fast-still-furious-all-still-hangs-together/rzvvCc8vH0SSRqnENfxp7N/story.html", critic: c, movie: m)
c = Critic.create!(name: "Adam Nayman", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.theglobeandmail.com/arts/film/film-reviews/fast-and-furious-6-the-high-octane-action-flick-as-soap-opera/article12095017/", critic: c, movie: m)
c = Critic.create!(name: "Jen Chaney", publication: "Washington Post")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "true", url: "http://www.washingtonpost.com/gog/movies/fast-and-furious-6,1210455/critic-review.html", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771246668)
CriticOpinion.create!(like: "false", url: "http://www.detroitnews.com/article/20130524/ENT02/305240020/1034/Review-Furious-6-dragged-down-by-lousy-lines-lazy-characters", critic: c, movie: m)

c = Critic.create!(name: "Anthony Lane", publication: "New Yorker")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "false", url: "http://www.newyorker.com/arts/reviews/film/star_trek_into_darkness_abrams", critic: c, movie: m)
c = Critic.create!(name: "Bob Mondello", publication: "NPR")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://www.npr.org/2013/05/18/185120495/new-trek-goes-into-darkness-but-not-much-deeper?ft=1&f=1045&utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Christopher Orr", publication: "The Atlantic")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "false", url: "http://www.theatlantic.com/entertainment/archive/2013/05/the-lightweight-appeal-of-i-star-trek-into-darkness-i/275970/", critic: c, movie: m)
c = Critic.create!(name: "J. R. Jones", publication: "Chicago Reader")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://www.chicagoreader.com/chicago/star-trek-into-darkness/Film?oid=9320817", critic: c, movie: m)
c = Critic.create!(name: "John Anderson", publication: "Wall Street Journal")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://online.wsj.com/page/2_1168.html?mod=2_1168", critic: c, movie: m)
c = Critic.create!(name: "Mick LaSalle", publication: "Hearst Newspapers")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://www.timesunion.com/living/article/Review-Star-Trek-Into-Darkness-both-funny-and-4518299.php", critic: c, movie: m)
c = Critic.create!(name: "Dana Stevens", publication: "Slate")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://feeds.slate.com/click.phdo?i=2dd2f3309e8de35f2e09a86d034c2657", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130516/OPINION03/305160301/1034/ent02/Review-Classic-villain-gives-Star-Trek-Into-Darkness-big-boost", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771190753)
CriticOpinion.create!(like: "true", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0516/Star-Trek-Into-Darkness-is-a-satisfying-sequel-video?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.denverpost.com/movies/ci_22834223/review-croods-awakenings-and-blunfrtd-make-fantastic-journey", critic: c, movie: m)
c = Critic.create!(name: "Bob Mondello", publication: "NPR")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.npr.org/2013/03/22/174957633/the-croods-3-d-cartoon-cavemen-for-the-whole-family?ft=1&f=1045", critic: c, movie: m)
c = Critic.create!(name: "Christopher Orr", publication: "The Atlantic")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.theatlantic.com/entertainment/archive/2013/02/cave-dwellers-and-pool-swimmers-at-the-berlin-film-festival/273258/", critic: c, movie: m)
c = Critic.create!(name: "Laremy Legel", publication: "Film.com")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.film.com/movies/review-the-croods", critic: c, movie: m)
c = Critic.create!(name: "Kate Erbland", publication: "MSN Movies")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://movies.msn.com/movies/movie-critic-reviews/the-croods/", critic: c, movie: m)
c = Critic.create!(name: "Stephen Whitty", publication: "Newark Star-Ledger")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.nj.com/entertainment/index.ssf/2013/03/the_croods_review_a_modern_sto.html", critic: c, movie: m)
c = Critic.create!(name: "Richard Corliss", publication: "TIME Magazine")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "false", url: "http://entertainment.time.com/2013/03/22/the-croods-a-post-modern-stone-age-family/", critic: c, movie: m)
c = Critic.create!(name: "Kevin Lally", publication: "Hollywood Reporter")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.filmjournal.com/filmjournal/content_display/reviews/major-releases/e3ice64385995bc4c70b08741482851356f", critic: c, movie: m)
c = Critic.create!(name: "Jody Mitori", publication: "St. Louis Post-Dispatch")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "true", url: "http://www.stltoday.com/entertainment/movies/reviews/cavemen-struggle-with-changing-times-in-the-croods/article_197c4347-6ee8-5eb9-946b-b9b6c2486d48.html", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(770818015)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/the-croods-a-bit-yabba-dabba-done-that-already/article10061045/", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "false", url: "http://www.richardroeper.com/reviews/manofsteel.aspx", critic: c, movie: m)
c = Critic.create!(name: "Christopher Orr", publication: "The Atlantic")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "true", url: "http://www.theatlantic.com/entertainment/archive/2013/06/-i-man-of-steel-i-the-i-dark-knight-i-ification-of-superman/276900/", critic: c, movie: m)
c = Critic.create!(name: "Rafer Guzman", publication: "Newsday")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "false", url: "http://www.newsday.com/entertainment/movies/man-of-steel-review-why-so-serious-1.5460119?utm_source=twitterfeed&utm_medium=twitter", critic: c, movie: m)
c = Critic.create!(name: "Matt Zoller Seitz", publication: "Chicago Sun-Times")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "true", url: "http://www.rogerebert.com/reviews/man-of-steel-2013", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130614/ENT02/306140018/1034/Review-Modern-Superman-myth-gets-visual-upgrade-well-made-Man-Steel-", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "false", url: "http://www.denverpost.com/movies/ci_23446778/movie-review-s-does-not-stand-soar-man", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "true", url: "http://www.theglobeandmail.com/arts/film/film-reviews/in-man-of-steel-the-first-victims-are-fun-and-wonder/article12508087/", critic: c, movie: m)
c = Critic.create!(name: "Ann Hornaday", publication: "Washington Post")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "false", url: "http://www.washingtonpost.com/goingoutguide/movies/man-of-steel-henry-cavill-stars-as-superman-in-this-bombastic-reboot/2013/06/12/6d77d5d0-d36c-11e2-a73e-826d299ff459_story.html", critic: c, movie: m)
c = Critic.create!(name: "Dana Stevens", publication: "Slate")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "true", url: "http://www.slate.com/articles/arts/movies/2013/06/man_of_steel_reviewed.html", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(770678819)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0613/Man-of-Steel-never-gets-off-the-ground?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "David Thomson", publication: "The New Republic")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "false", url: "http://www.newrepublic.com/article/113144/gatsby-speaks-beyond-grave", critic: c, movie: m)
c = Critic.create!(name: "Joe Baltake", publication: "Passionate Moviegoer")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "false", url: "http://thepassionatemoviegoer.blogspot.com/2013/05/gatsbyghastly.html", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "false", url: "http://www.cnn.com/2013/05/10/showbiz/movies/great-gatsby-review-tom-charity/index.html?iref=allsearch", critic: c, movie: m)
c = Critic.create!(name: "Christopher Orr", publication: "The Atlantic")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "false", url: "http://www.theatlantic.com/entertainment/archive/2013/05/a-grating-em-great-gatsby-em/275744/", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "true", url: "http://www.richardroeper.com/reviews/thegreatgatsby.aspx", critic: c, movie: m)
c = Critic.create!(name: "Connie Ogle", publication: "Miami Herald")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "false", url: "http://www.miami.com/great-gatsby-pg-13-article", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130510/OPINION03/305100315/1034/ENT02/Review-Great-Gatsby-goes-big-comes-off-too-cool-connect", critic: c, movie: m)
c = Critic.create!(name: "Rick Groen", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "true", url: "http://www.theglobeandmail.com/arts/film/film-reviews/the-great-gatsby-a-great-adaptation-of-a-great-novel-and-just-shy-of-a-great-film/article11823125/", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "New York Magazine")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "true", url: "http://www.vulture.com/2013/05/movie-review-the-great-gatsby.html", critic: c, movie: m)
c = Critic.create!(name: "Dana Stevens", publication: "Slate")
m = Movie.find_by_rt_id(771240552)
CriticOpinion.create!(like: "true", url: "http://feeds.slate.com/click.phdo?i=75f5ebe7abdf68884198aebb24d0fcdf", critic: c, movie: m)
c = Critic.create!(name: "Trevor Johnston", publication: "Time Out")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/london/film/identity-thief", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "true", url: "http://www.cnn.com/2013/02/08/showbiz/movies/identity-thief-review-charity/index.html?iref=allsearch", critic: c, movie: m)
c = Critic.create!(name: "Linda Barnard", publication: "Toronto Star")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.thestar.com/entertainment/movies/2013/02/07/movie_review_identity_thief.html", critic: c, movie: m)
c = Critic.create!(name: "Andrew O'Hehir", publication: "Salon.com")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.salon.com/2013/02/08/identity_thief_stole_my_brain_and_now_i_hate_everything/", critic: c, movie: m)
c = Critic.create!(name: "Rene Rodriguez", publication: "Miami Herald")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.miami.com/039indentity-thief039-r-article", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.richardroeper.com/reviews/identitythief.aspx", critic: c, movie: m)
c = Critic.create!(name: "J. R. Jones", publication: "Chicago Reader")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "true", url: "http://www.chicagoreader.com/chicago/identity-thief/Film?oid=8563406", critic: c, movie: m)
c = Critic.create!(name: "Dana Stevens", publication: "Slate")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.slate.com/articles/arts/movies/2013/02/melissa_mccarthy_in_identity_thief_reviewed.html", critic: c, movie: m)
c = Critic.create!(name: "James Berardinelli", publication: "ReelViews")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.reelviews.net/php_review_template.php?identifier=2585", critic: c, movie: m)
c = Critic.create!(name: "Christy Lemire", publication: "Associated Press")
m = Movie.find_by_rt_id(771270981)
CriticOpinion.create!(like: "false", url: "http://www.boston.com/ae/movies/2013/02/07/review-identity-thief-has-charge/jrSVGjfPdVHLrqugey6CDO/story.html", critic: c, movie: m)
c = Critic.create!(name: "Peter Hartlaub", publication: "San Francisco Chronicle")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://www.sfchronicle.com/movies/article/G-I-Joe-Retaliation-review-just-playing-4392266.php", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/gi-joe-retaliation-an-explosive-flick-that-disregards-space-and-time/article10439268/", critic: c, movie: m)
c = Critic.create!(name: "Glenn Kenny", publication: "MSN Movies")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "true", url: "http://movies.msn.com/movies/movie-critic-reviews/gi-joe-retaliation/", critic: c, movie: m)
c = Critic.create!(name: "Keith Uhlich", publication: "Time Out New York")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/us/film/g-i-joe-retaliation-movie-review", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://www.detroitnews.com/article/20130328/OPINION03/303280302/1034/ent02/Review-G-Joe-Retaliation-bad-should-shot", critic: c, movie: m)
c = Critic.create!(name: "Richard Corliss", publication: "TIME Magazine")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "true", url: "http://entertainment.time.com/2013/03/28/g-i-joe-retaliation-make-that-redemption/", critic: c, movie: m)
c = Critic.create!(name: "Mark Jenkins", publication: "NPR")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://www.npr.org/2013/03/28/175276912/retaliation-harsh-payback-for-poor-g-i-joe", critic: c, movie: m)
c = Critic.create!(name: "Neil Genzlinger", publication: "New York Times")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://movies.nytimes.com/2013/03/29/movies/gi-joe-retaliation-directed-by-jon-m-chu.html?partner=rss&emc=rss", critic: c, movie: m)
c = Critic.create!(name: "Joe Morgenstern", publication: "Wall Street Journal")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://online.wsj.com/article/SB10001424127887324685104578388324175793556.html", critic: c, movie: m)
c = Critic.create!(name: "Bill Goodykoontz", publication: "Arizona Republic")
m = Movie.find_by_rt_id(771241227)
CriticOpinion.create!(like: "false", url: "http://www.azcentral.com/thingstodo/movies/articles/20130326g-i-joe-retaliation-movie-review-goodykoontz.html", critic: c, movie: m)
c = Critic.create!(name: "J. R. Jones", publication: "Chicago Reader")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "true", url: "http://www.chicagoreader.com/chicago/the-hangover-part-iii/Film?oid=9381492", critic: c, movie: m)
c = Critic.create!(name: "Joel Arnold", publication: "NPR")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.npr.org/2013/05/24/185531864/this-time-its-a-dull-ache-of-a-hangover?ft=1&f=1045&utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.cnn.com/2013/05/23/showbiz/movies/hangover-iii-review-charity/index.html?iref=allsearch", critic: c, movie: m)
c = Critic.create!(name: "James Rocchi", publication: "MSN Movies")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://movies.msn.com/movies/movie-critic-reviews/the-hangover-part-iii/", critic: c, movie: m)
c = Critic.create!(name: "Rene Rodriguez", publication: "Miami Herald")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.miami.com/039the-hangover-part-iii039-r-article", critic: c, movie: m)
c = Critic.create!(name: "Rick Groen", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/the-hangover-part-iii-weirdly-fascinatingly-bad/article12098826/", critic: c, movie: m)
c = Critic.create!(name: "John Anderson", publication: "Wall Street Journal")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "true", url: "http://online.wsj.com/article/SB10001424127887324659404578501004209538838.html?mod=WSJ_ArtsEnt_LifestyleArtEnt_6", critic: c, movie: m)
c = Critic.create!(name: "Michael O'Sullivan", publication: "Washington Post")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.washingtonpost.com/gog/movies/the-hangover-part-iii,1227027/critic-review.html", critic: c, movie: m)
c = Critic.create!(name: "James Berardinelli", publication: "ReelViews")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.reelviews.net/php_review_template.php?identifier=2621&utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771268395)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0523/The-Hangover-Part-III-shows-the-series-has-worn-out-its-welcome?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "Guy Lodge", publication: "Time Out")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/london/film/olympus-has-fallen", critic: c, movie: m)
c = Critic.create!(name: "Drew Hunt", publication: "Chicago Reader")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://www.chicagoreader.com/chicago/olympus-has-fallen/Film?oid=8972818", critic: c, movie: m)
c = Critic.create!(name: "David Denby", publication: "New Yorker")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://www.newyorker.com/arts/critics/cinema/2013/04/01/130401crci_cinema_denby", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "Vulture")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://www.vulture.com/2013/03/movie-review-olympus-has-fallen.html", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "New York Magazine")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://www.vulture.com/2013/03/movie-review-olympus-has-fallen.html", critic: c, movie: m)
c = Critic.create!(name: "Robert Abele", publication: "Los Angeles Times")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-mn-olympus-fallen-20130322,0,2844491.story", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://www.richardroeper.com/reviews/olympushasfallen.aspx", critic: c, movie: m)
c = Critic.create!(name: "Glenn Kenny", publication: "MSN Movies")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "false", url: "http://movies.msn.com/movies/movie-critic-reviews/olympus-has-fallen/", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "true", url: "http://www.theglobeandmail.com/arts/film/film-reviews/olympus-has-fallen-a-retro-thriller-with-plenty-of-guilty-pleasures/article10072460/", critic: c, movie: m)
c = Critic.create!(name: "Adam Graham", publication: "Detroit News")
m = Movie.find_by_rt_id(771320125)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130322/ENT02/303220307/1034/ent02/Review-Olympus-Has-Fallen-brings-Die-Hard-White-House", critic: c, movie: m)
c = Critic.create!(name: "James Berardinelli", publication: "ReelViews")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.reelviews.net/php_review_template.php?identifier=2623&utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0524/Epic-has-entertaining-voice-actors-but-ho-hum-visuals?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "Zachary Wigon", publication: "Village Voice")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "true", url: "http://www.villagevoice.com/2013-05-22/film/epic/?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Glenn Kenny", publication: "MSN Movies")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://movies.msn.com/movies/movie-critic-reviews/epic.2/", critic: c, movie: m)
c = Critic.create!(name: "Stephen Whitty", publication: "Newark Star-Ledger")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.nj.com/entertainment/index.ssf/2013/05/epic_review_a_daze_of_vines_an.html?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Dave McGinn", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/great-visuals-but-epic-isnt-all-that-epic/article12093200/", critic: c, movie: m)
c = Critic.create!(name: "Michael O'Sullivan", publication: "Washington Post")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "true", url: "http://www.washingtonpost.com/gog/movies/epic-in-3d,1211399/critic-review.html", critic: c, movie: m)
c = Critic.create!(name: "Tom Russo", publication: "Boston Globe")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.boston.com/ae/movies/2013/05/23/epic-only-sees-the-big-picture/pI8Q6UTLw5s0YeAZDJPkDI/story.html", critic: c, movie: m)
c = Critic.create!(name: "Steven Rea", publication: "Philadelphia Inquirer")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.philly.com/philly/entertainment/movies/20130524__Epic___An_animated_good-vs_-evil_action-fantasy.html", critic: c, movie: m)
c = Critic.create!(name: "Betsy Sharkey", publication: "Los Angeles Times")
m = Movie.find_by_rt_id(771249677)
CriticOpinion.create!(like: "false", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-mn-epic-review-beyonce-aziz-ansari-jason-sudeikis-amanda-seyfried-20130524,0,2463019.story", critic: c, movie: m)
c = Critic.create!(name: "David Denby", publication: "New Yorker")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.newyorker.com/arts/reviews/film/42_helgeland", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.richardroeper.com/reviews/42.aspx", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.denverpost.com/movies/ci_22997842/42-gives-baseball-great-jackie-robinson-but-also", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0412/42-is-a-dull-treatment-of-Jackie-Robinson-s-story?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "Laremy Legel", publication: "Film.com")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.film.com/movies/review-42", critic: c, movie: m)
c = Critic.create!(name: "Stephen Whitty", publication: "Newark Star-Ledger")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.nj.com/entertainment/index.ssf/2013/04/42_review_the_jackie_robinson.html", critic: c, movie: m)
c = Critic.create!(name: "Rick Groen", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/42-touches-all-the-bases-but-fails-to-score/article11068250/", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130412/OPINION03/304120318/1034/ENT02/Review-42-Jackie-Robinson-Story-tells-story-ballplayer-who-changed-history", critic: c, movie: m)
c = Critic.create!(name: "Lou Lumenick", publication: "New York Post")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.nypost.com/p/entertainment/movies/is_an_inspiring_tribute_to_jackie_5uxYbtAvO9RoQUyySd6SyO", critic: c, movie: m)
c = Critic.create!(name: "Ann Hornaday", publication: "Washington Post")
m = Movie.find_by_rt_id(771305747)
CriticOpinion.create!(like: "true", url: "http://www.washingtonpost.com/gog/movies/42,1228915/critic-review.html", critic: c, movie: m)
c = Critic.create!(name: "Anthony Lane", publication: "New Yorker")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "false", url: "http://www.newyorker.com/arts/reviews/film/oblivion_kosinski", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "Vulture")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "false", url: "http://www.vulture.com/2013/04/movie-review-oblivion.html", critic: c, movie: m)
c = Critic.create!(name: "Ignatiy Vishnevetsky", publication: "Chicago Sun-Times")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "false", url: "http://www.rogerebert.com/reviews/oblivion-2013?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "true", url: "http://www.richardroeper.com/reviews/oblivion.aspx", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "true", url: "http://www.cnn.com/2013/04/19/showbiz/movies/cruise-oblivion-review-charity/index.html", critic: c, movie: m)
c = Critic.create!(name: "J. R. Jones", publication: "Chicago Reader")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "true", url: "http://www.chicagoreader.com/chicago/oblivion/Film?oid=9022334", critic: c, movie: m)
c = Critic.create!(name: "Andrew O'Hehir", publication: "Salon.com")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "true", url: "http://www.salon.com/2013/04/19/pick_of_the_week_oblivion_tom_cruises_gorgeous_sci_fi_allegory/?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Rick Groen", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/oblivion-a-multimillion-dollar-exercise-in-competence/article11378008/", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130419/OPINION03/304190311/1034/ENT02/Review-Familiar-Oblivion-keeps-action-special-effects-pumping", critic: c, movie: m)
c = Critic.create!(name: "Stephen Whitty", publication: "Newark Star-Ledger")
m = Movie.find_by_rt_id(771245728)
CriticOpinion.create!(like: "false", url: "http://www.nj.com/entertainment/index.ssf/2013/04/oblivion_review_tom_cruise.html?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Alonso Duralde", publication: "The Wrap")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://www.thewrap.com/movies/column-post/now-you-see-me-review-magic-themed-heist-movie-maybe-too-much-its-sleeve-94751", critic: c, movie: m)
c = Critic.create!(name: "Scott Foundas", publication: "Variety")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://variety.com/2013/film/reviews/film-review-now-you-see-me-1200490336/?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0531/Now-You-See-Me-has-a-great-premise-but-doesn-t-follow-through?nav=397-csm_subcategory-topStories", critic: c, movie: m)
c = Critic.create!(name: "Scott Bowles", publication: "USA Today")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://rssfeeds.usatoday.com/~r/UsatodaycomMovies-TopStories/~3/AkRDRtGDJY8/?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Peter Howell", publication: "Toronto Star")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://www.thestar.com/entertainment/movies/2013/05/31/now_you_see_me_has_nothing_up_its_sleeve_review.html?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/now-you-see-me-proves-to-be-less-than-meets-the-eye/article12267836/", critic: c, movie: m)
c = Critic.create!(name: "Gary Goldstein", publication: "Los Angeles Times")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "false", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-now-you-see-me-20130531,0,5694710.story", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20130531/ENT02/305310004?utm_source=feedly", critic: c, movie: m)
c = Critic.create!(name: "Ignatiy Vishnevetsky", publication: "Chicago Sun-Times")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "true", url: "http://www.rogerebert.com/reviews/now-you-see-me-2013", critic: c, movie: m)
c = Critic.create!(name: "Stephanie Merry", publication: "Washington Post")
m = Movie.find_by_rt_id(771245005)
CriticOpinion.create!(like: "true", url: "http://www.washingtonpost.com/lifestyle/style/now-you-see-me-movie-review/2013/05/30/c7e5d2d8-c926-11e2-9245-773c0123c027_story.html", critic: c, movie: m)
c = Critic.create!(name: "Melissa Anderson", publication: "Time Out")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/film/reviews/85390/baby_mama.html", critic: c, movie: m)

c = Critic.create!(name: "Bob Mondello", publication: "NPR.org")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "false", url: "http://www.npr.org/templates/story/story.php?storyId=89810930", critic: c, movie: m)
c = Critic.create!(name: "Carina Chocano", publication: "Los Angeles Times")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "true", url: "http://www.calendarlive.com/movies/reviews/cl-et-baby25apr25,0,6317912.story", critic: c, movie: m)
c = Critic.create!(name: "Joe Baltake", publication: "Passionate Moviegoer")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "false", url: "http://thepassionatemoviegoer.blogspot.com/2008/04/baby-mama-makes-do-do.html", critic: c, movie: m)
c = Critic.create!(name: "Lisa Schwarzbaum", publication: "Entertainment Weekly")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "true", url: "http://www.ew.com/ew/article/0,,20195624,00.html", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Ebert & Roeper")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "true", url: "", critic: c, movie: m)
c = Critic.create!(name: "Joe Morgenstern", publication: "Wall Street Journal")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "false", url: "http://online.wsj.com/article/SB120908724598943787.html", critic: c, movie: m)
c = Critic.create!(name: "Claudia Puig", publication: "USA Today")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "true", url: "http://www.usatoday.com/community/utils/idmap/31553838.story", critic: c, movie: m)
c = Critic.create!(name: "Richard Corliss", publication: "TIME Magazine")
m = Movie.find_by_rt_id(770681823)
CriticOpinion.create!(like: "true", url: "http://www.time.com/time/arts/article/0,8599,1735059,00.html", critic: c, movie: m)
c = Critic.create!(name: "Drew Hunt", publication: "Chicago Reader")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.chicagoreader.com/chicago/safe-haven/Film?oid=8618356", critic: c, movie: m)
c = Critic.create!(name: "Trevor Johnston", publication: "Time Out")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/london/film/safe-haven", critic: c, movie: m)
c = Critic.create!(name: "Rex Reed", publication: "New York Observer")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://observer.com/2013/02/low-tide-safe-haven-is-a-romantic-thriller-that-washes-out-before-sunset/", critic: c, movie: m)
c = Critic.create!(name: "Michael Granberry", publication: "Dallas Morning News")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.dallasnews.com/entertainment/movies/reviews/20130214-safe-haven-is-melodrama-with-a-capital-m-c.ece", critic: c, movie: m)
c = Critic.create!(name: "Kate Erbland", publication: "MSN Movies")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://movies.msn.com/movies/movie-critic-reviews/safe-haven.3/", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0214/Safe-Haven-is-a-sudsy-scary-weepfest?nav=397-csm_subcategory-leadStory", critic: c, movie: m)
c = Critic.create!(name: "Laremy Legel", publication: "Film.com")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.film.com/movies/safe-haven-review", critic: c, movie: m)
c = Critic.create!(name: "Melissa Anderson", publication: "Village Voice")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.villagevoice.com/2013-02-13/film/safe-haven/", critic: c, movie: m)
c = Critic.create!(name: "Peter Travers", publication: "Rolling Stone")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.rollingstone.com/movies/reviews/safe-haven-20130214", critic: c, movie: m)
c = Critic.create!(name: "Rick Groen", publication: "Globe and Mail")
m = Movie.find_by_rt_id(770893918)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/safe-haven-a-pastel-hallmark-card-for-valentines-day/article8600127/", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.richardroeper.com/reviews/agooddaytodiehard.aspx", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "New York Magazine")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.vulture.com/2013/02/movie-review-a-good-day-to-die-hard.html", critic: c, movie: m)
c = Critic.create!(name: "Chris Vognar", publication: "Dallas Morning News")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "true", url: "http://www.dallasnews.com/entertainment/movies/reviews/20130213-a-good-day-to-die-hard-is-a-nuclear-blast-of-retro-activity-b-.ece", critic: c, movie: m)
c = Critic.create!(name: "Joe Morgenstern", publication: "Wall Street Journal")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://online.wsj.com/article/SB10001424127887323478004578303922074172766.html", critic: c, movie: m)
c = Critic.create!(name: "Dana Stevens", publication: "Slate")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://feeds.slate.com/click.phdo?i=5229c1005c4d1e597749b16f608ed261", critic: c, movie: m)
c = Critic.create!(name: "Ian Buckwalter", publication: "NPR")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.npr.org/2013/02/14/171833011/a-good-day-wake-me-tomorrow?ft=1&f=1045", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0214/A-Good-Day-to-Die-Hard-makes-John-McClane-a-little-too-invincible-video?nav=397-csm_subcategory-topStories", critic: c, movie: m)
c = Critic.create!(name: "Lisa Kennedy", publication: "Denver Post")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.denverpost.com/movies/ci_22584265/too-little-yipee-lot-ki-yay-die-hard", critic: c, movie: m)
c = Critic.create!(name: "James Berardinelli", publication: "ReelViews")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.reelviews.net/php_review_template.php?identifier=2588", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771257607)
CriticOpinion.create!(like: "false", url: "http://www.detroitnews.com/article/20130214/OPINION03/302140310/1034/ent02/Review-Action-packed-Good-Day-Die-Hard-lacks-humor-personality", critic: c, movie: m)
c = Critic.create!(name: "David Thomson", publication: "The New Republic")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://www.newrepublic.com/article/112435/what-are-all-our-zombies-telling-us-review-warm-bodies", critic: c, movie: m)
c = Critic.create!(name: "Cath Clarke", publication: "Time Out")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/london/film/warm-bodies", critic: c, movie: m)
c = Critic.create!(name: "Richard Roeper", publication: "Richard Roeper.com")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://www.richardroeper.com/reviews/warmbodies.aspx", critic: c, movie: m)
c = Critic.create!(name: "Lisa Schwarzbaum", publication: "Entertainment Weekly")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://www.ew.com/ew/article/0,,20483133_20657882,00.html", critic: c, movie: m)
c = Critic.create!(name: "Peter Travers", publication: "Rolling Stone")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "false", url: "http://www.rollingstone.com/movies/reviews/warm-bodies-20130201", critic: c, movie: m)
c = Critic.create!(name: "Christopher Orr", publication: "The Atlantic")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://www.theatlantic.com/entertainment/archive/2013/02/warm-bodies-a-heartfelt-zombie-love-story/272755/#disqus_thread", critic: c, movie: m)
c = Critic.create!(name: "Andrew O'Hehir", publication: "Salon.com")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "false", url: "http://www.salon.com/2013/02/01/warm_bodies_love_with_an_emo_zombie/", critic: c, movie: m)
c = Critic.create!(name: "Mary F. Pols", publication: "TIME Magazine")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://entertainment.time.com/2013/02/01/warm-bodies-a-hot-zom-rom-com/", critic: c, movie: m)
c = Critic.create!(name: "Stephen Whitty", publication: "Newark Star-Ledger")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "true", url: "http://www.nj.com/entertainment/index.ssf/2013/02/warm_bodies_review_life_after.html", critic: c, movie: m)
c = Critic.create!(name: "Mick LaSalle", publication: "San Francisco Chronicle")
m = Movie.find_by_rt_id(771238285)
CriticOpinion.create!(like: "false", url: "http://www.sfgate.com/movies/article/Warm-Bodies-review-Zombie-in-love-4240150.php", critic: c, movie: m)
c = Critic.create!(name: "Nigel Floyd", publication: "Time Out")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/london/film/jack-the-giant-slayer", critic: c, movie: m)
c = Critic.create!(name: "David Edelstein", publication: "Vulture")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "true", url: "http://www.vulture.com/2013/02/movie-review-jack-the-giant-slayer.html", critic: c, movie: m)
c = Critic.create!(name: "Peter Rainer", publication: "Christian Science Monitor")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0301/Jack-the-Giant-Slayer-is-more-ho-hum-than-fee-fi-fo-fum?nav=397-csm_subcategory-topStories", critic: c, movie: m)
c = Critic.create!(name: "Tom Charity", publication: "CNN.com")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "true", url: "http://www.cnn.com/2013/03/01/showbiz/movies/jack-giant-slayer-review/index.html?iref=allsearch", critic: c, movie: m)
c = Critic.create!(name: "Mary F. Pols", publication: "TIME Magazine")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "false", url: "http://entertainment.time.com/2013/02/28/jack-the-giant-slayer-fee-fi-ho-hum/", critic: c, movie: m)
c = Critic.create!(name: "Stephen Whitty", publication: "Newark Star-Ledger")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "true", url: "http://www.nj.com/entertainment/index.ssf/2013/03/jack_the_giant_slayer_review_a.html", critic: c, movie: m)
c = Critic.create!(name: "Linda Barnard", publication: "Toronto Star")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "true", url: "http://www.thestar.com/entertainment/movies/2013/03/01/jack_the_giant_slayer_is_full_of_beans_review.html", critic: c, movie: m)
c = Critic.create!(name: "Liam Lacey", publication: "Globe and Mail")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/jack-the-giant-slayer-how-many-cgid-fairy-tales-can-we-take/article9158503/", critic: c, movie: m)
c = Critic.create!(name: "Tom Long", publication: "Detroit News")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "false", url: "http://www.detroitnews.com/article/20130301/OPINION03/303010305/1034/ENT02/Review-Jack-Giant-Slayer-unnecessary-uninvolving-underwhelming", critic: c, movie: m)
c = Critic.create!(name: "Michael O'Sullivan", publication: "Washington Post")
m = Movie.find_by_rt_id(771189410)
CriticOpinion.create!(like: "false", url: "http://www.washingtonpost.com/gog/movies/jack-the-giant-slayer-3d,1206568/critic-review.html", critic: c, movie: m)
