# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

CriticOpinion.delete_all
Movie.delete_all
Critic.delete_all

Movie.create!(title: "World War Z", year: 2013, description: "The story revolves around United Nations employee Gerry Lane (Pitt), who traverses the world in a race against time to stop a pandemic that is toppling armies and governments and threatening to decimate humanity itself. (C) Paramount", rt_id: 770785616)
Movie.create!(title: "Monsters University", year: 2013, description: "Mike Wazowski and James P. Sullivan are an inseparable pair, but that wasn\'t always the case. From the moment these two mismatched monsters met they couldn\'t stand each other. \"Monsters University\" unlocks the door to how Mike and Sulley overcame their differences and became the best of friends. -- (C) Walt Disney", rt_id: 771238418)
Movie.create!(title: "Maniac", year: 2013, description: "Just when the streets seemed safe, a serial killer with a fetish for scalps is back and on the hunt. Frank (Elijah Wood) is the withdrawn owner of a mannequin store, but his life changes when young artist Anna (Nora Arnezeder) appears asking for his help with her new exhibition. As their friendship develops and Frank\'s obsession escalates, it becomes clear that she has unleashed a long-repressed compulsion to stalk and kill. A 21st century Jack the Ripper set in present day LA, Franck Khalfoun\'s Maniac is a re-boot of the William Lustig cult film considered by many to be the most suspensseful slasher movie ever made - an intimate, visually daring, psychologically complex and projoundly horrific trip into the downward spiralling nightmare of a killer and his victims. -- (C) IFC", rt_id: 771307887)
Movie.create!(title: "A Hijacking", year: 2013, description: "The cargo ship MV Rozen is heading for harbour when it is hijacked by Somali pirates in the Indian Ocean. Amongst the men on board are the ship\'s cook Mikkel (Pilou Asbaek) and the engineer Jan (Roland Moller), who along with the rest of the seamen are taken hostage in a cynical game of life and death. With the demand for a ransom of millions of dollars a psychological drama unfolds between the CEO of the shipping company (Soren Malling) and the Somali pirates. (c) Magnolia", rt_id: 771315311)
Movie.create!(title: "Unfinished Song", year: 2013, description: "UNFINISHED SONG is the funny and uplifting story of Arthur (Terence Stamp), a curmudgeon old soul perfectly content with sticking to his dull daily routine until his beloved wife (Vanessa Redgrave) introduces him to a spirited local singing group led by the youthful and charming Elizabeth (Gemma Arterton). This unexpected friendship and his discovery of music revitalizes Arthur\'s passion for new adventures and shows us all life should be celebrated at any age. (c) Weinstein", rt_id: 771324801)
Movie.create!(title: "How To Make Money Selling Drugs", year: 2013, description: "A shockingly candid examination of how a street dealer can rise to cartel lord with relative ease, How to Make Money Selling Drugs is an insider\'s guide to the violent but extremely lucrative drug industry. Told from the perspective of former drug dealers, and featuring interviews with rights advocates Russell Simmons, Susan Sarandon, and David Simon (creator of \"The Wire\"), the film gives you the lessons you need to start your own drug empire while exposing the corruption behind the \"war on drugs.\" (c) Tribeca Films", rt_id: 771315033)
Movie.create!(title: "White House Down", year: 2013, description: "The White House is under siege in this action thriller from Independence Day director Roland Emmerich and The Amazing Spider-Man\'s writer James Vanderbilt in this Sony Pictures release. Channing Tatum stars. ~ Jeremy Wheeler, Rovi", rt_id: 771307102)
Movie.create!(title: "The Heat", year: 2013, description: "Uptight FBI special agent Sarah Ashburn is paired with testy Boston cop Shannon Mullins in order to take down a ruthless drug lord. The hitch: neither woman has ever had a partner -- or a friend for that matter.", rt_id: 771308691)
Movie.create!(title: "I'm So Excited!", year: 2013, description: "A technical failure has endangered the lives of the people on board Peninsula Flight 2549. The pilots are striving, along with their colleagues in the Control Center, to find a solution. The flight attendants and the chief steward are atypical, baroque characters who, in the face of danger, try to forget their own personal problems and devote themselves body and soul to the task of making the flight as enjoyable as possible for the passengers, while they wait for a solution. Life in the clouds is as complicated as it is at ground level, and for the same reasons, which could be summarized in two: sex and death. (c) Sony Classics", rt_id: 771323626)
Movie.create!(title: "Byzantium", year: 2013, description: "BYZANTIUM is director Neil Jordan\'s (Interview with the Vampire, The Crying Game) sexy and stylish fantasy thriller about mother and daughter vampires dealing with the pitfalls of eternal life. Two mysterious women seek refuge in a run-down coastal resort. Clara (Gemma Arterton) meets lonely Noel (Daniel Mays), who provides shelter in his deserted guesthouse, Byzantium. Schoolgirl Eleanor (Saoirse Ronan, Hanna, Atonement) befriends Frank (Caleb Landry Jones) and tells him their lethal secret: They were born 200 years ago and survive on human blood. As knowledge of their secret spreads, their past catches up on them with deathly consequence. Also starring Sam Riley and Jonny Lee Miller. (c) IFC", rt_id: 771303874)
c = Critic.create!(name: "William Goss", publication: "Film.com")
m = Movie.find_by_rt_id(770785616)
CriticOpinion.create!(like: "true", url: "http://www.film.com/movies/world-war-z-review", critic: c, movie: m)
c = Critic.create!(name: "Scott Foundas", publication: "Variety")
m = Movie.find_by_rt_id(770785616)
CriticOpinion.create!(like: "true", url: "http://variety.com/2013/film/reviews/world-war-z-review-1200492031/", critic: c, movie: m)
c = Critic.create!(name: "Todd McCarthy", publication: "Hollywood Reporter")
m = Movie.find_by_rt_id(770785616)
CriticOpinion.create!(like: "true", url: "http://www.hollywoodreporter.com/movie/world-war-z/review/562560", critic: c, movie: m)
c = Critic.create!(name: "Justin Chang", publication: "Variety")
m = Movie.find_by_rt_id(771238418)
CriticOpinion.create!(like: "true", url: "http://variety.com/2013/film/reviews/film-review-monsters-university-1200494184/", critic: c, movie: m)
c = Critic.create!(name: "Todd McCarthy", publication: "Hollywood Reporter")
m = Movie.find_by_rt_id(771238418)
CriticOpinion.create!(like: "false", url: "http://www.hollywoodreporter.com/movie/monsters-university/review/564746", critic: c, movie: m)
c = Critic.create!(name: "Alonso Duralde", publication: "The Wrap")
m = Movie.find_by_rt_id(771238418)
CriticOpinion.create!(like: "true", url: "http://www.thewrap.com/movies/column-post/monsters-university-review-wait-didnt-we-see-all-internship-96186", critic: c, movie: m)
c = Critic.create!(name: "Guy Lodge", publication: "Time Out")
m = Movie.find_by_rt_id(771307887)
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/london/film/maniac", critic: c, movie: m)
c = Critic.create!(name: "Megan Lehmann", publication: "Hollywood Reporter")
m = Movie.find_by_rt_id(771307887)
CriticOpinion.create!(like: "true", url: "http://www.hollywoodreporter.com/review/maniac-elijah-wood-cannes-review-329836", critic: c, movie: m)
c = Critic.create!(name: "Cath Clarke", publication: "Time Out")
m = Movie.find_by_rt_id(771315311)
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/london/film/a-hijacking", critic: c, movie: m)
c = Critic.create!(name: "Guy Lodge", publication: "Variety")
m = Movie.find_by_rt_id(771315311)
CriticOpinion.create!(like: "true", url: "http://www.variety.com/review/VE1117948190/", critic: c, movie: m)
c = Critic.create!(name: "Trevor Johnston", publication: "Time Out")
m = Movie.find_by_rt_id(771324801)
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/london/film/song-for-marion", critic: c, movie: m)
c = Critic.create!(name: "Linda Holmes", publication: "NPR")
m = Movie.find_by_rt_id(771315033)
CriticOpinion.create!(like: "true", url: "http://www.npr.org/blogs/monkeysee/2012/09/09/160828846/tiff-12-a-new-documentary-explains-how-to-make-money-selling-drugs?ft=1&f=1045", critic: c, movie: m)
c = Critic.create!(name: "Ben Walters", publication: "Time Out")
m = Movie.find_by_rt_id(771323626)
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/london/film/im-so-excited", critic: c, movie: m)
c = Critic.create!(name: "Cath Clarke", publication: "Time Out")
m = Movie.find_by_rt_id(771303874)
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/london/film/byzantium-2013", critic: c, movie: m)
c = Critic.create!(name: "Jordan Hoffman", publication: "Film.com")
m = Movie.find_by_rt_id(771303874)
CriticOpinion.create!(like: "false", url: "http://www.film.com/movies/byzantium-review-2012", critic: c, movie: m)
