# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Movie.delete_all
Critic.delete_all
CriticOpinion.delete_all

Movie.create(title: "World War Z", year: 2013, description: "The story revolves around United Nations employee Gerry Lane (Pitt), who traverses the world in a race against time to stop a pandemic that is toppling armies and governments and threatening to decimate humanity itself. (C) Paramount", rt_id: 770785616)
Movie.create(title: "Monsters University", year: 2013, description: "Mike Wazowski and James P. Sullivan are an inseparable pair, but that wasn\'t always the case. From the moment these two mismatched monsters met they couldn\'t stand each other. \"Monsters University\" unlocks the door to how Mike and Sulley overcame their differences and became the best of friends. -- (C) Walt Disney", rt_id: 771238418)
Movie.create(title: "Maniac", year: 2013, description: "Just when the streets seemed safe, a serial killer with a fetish for scalps is back and on the hunt. Frank (Elijah Wood) is the withdrawn owner of a mannequin store, but his life changes when young artist Anna (Nora Arnezeder) appears asking for his help with her new exhibition. As their friendship develops and Frank\'s obsession escalates, it becomes clear that she has unleashed a long-repressed compulsion to stalk and kill. A 21st century Jack the Ripper set in present day LA, Franck Khalfoun\'s Maniac is a re-boot of the William Lustig cult film considered by many to be the most suspensseful slasher movie ever made - an intimate, visually daring, psychologically complex and projoundly horrific trip into the downward spiralling nightmare of a killer and his victims. -- (C) IFC", rt_id: 771307887)
Movie.create(title: "A Hijacking", year: 2013, description: "The cargo ship MV Rozen is heading for harbour when it is hijacked by Somali pirates in the Indian Ocean. Amongst the men on board are the ship\'s cook Mikkel (Pilou Asbaek) and the engineer Jan (Roland Moller), who along with the rest of the seamen are taken hostage in a cynical game of life and death. With the demand for a ransom of millions of dollars a psychological drama unfolds between the CEO of the shipping company (Soren Malling) and the Somali pirates. (c) Magnolia", rt_id: 771315311)
Movie.create(title: "Unfinished Song", year: 2013, description: "UNFINISHED SONG is the funny and uplifting story of Arthur (Terence Stamp), a curmudgeon old soul perfectly content with sticking to his dull daily routine until his beloved wife (Vanessa Redgrave) introduces him to a spirited local singing group led by the youthful and charming Elizabeth (Gemma Arterton). This unexpected friendship and his discovery of music revitalizes Arthur\'s passion for new adventures and shows us all life should be celebrated at any age. (c) Weinstein", rt_id: 771324801)
Movie.create(title: "How To Make Money Selling Drugs", year: 2013, description: "A shockingly candid examination of how a street dealer can rise to cartel lord with relative ease, How to Make Money Selling Drugs is an insider\'s guide to the violent but extremely lucrative drug industry. Told from the perspective of former drug dealers, and featuring interviews with rights advocates Russell Simmons, Susan Sarandon, and David Simon (creator of \"The Wire\"), the film gives you the lessons you need to start your own drug empire while exposing the corruption behind the \"war on drugs.\" (c) Tribeca Films", rt_id: 771315033)
Movie.create(title: "White House Down", year: 2013, description: "The White House is under siege in this action thriller from Independence Day director Roland Emmerich and The Amazing Spider-Man\'s writer James Vanderbilt in this Sony Pictures release. Channing Tatum stars. ~ Jeremy Wheeler, Rovi", rt_id: 771307102)
Movie.create(title: "The Heat", year: 2013, description: "Uptight FBI special agent Sarah Ashburn is paired with testy Boston cop Shannon Mullins in order to take down a ruthless drug lord. The hitch: neither woman has ever had a partner -- or a friend for that matter.", rt_id: 771308691)
Movie.create(title: "I'm So Excited!", year: 2013, description: "A technical failure has endangered the lives of the people on board Peninsula Flight 2549. The pilots are striving, along with their colleagues in the Control Center, to find a solution. The flight attendants and the chief steward are atypical, baroque characters who, in the face of danger, try to forget their own personal problems and devote themselves body and soul to the task of making the flight as enjoyable as possible for the passengers, while they wait for a solution. Life in the clouds is as complicated as it is at ground level, and for the same reasons, which could be summarized in two: sex and death. (c) Sony Classics", rt_id: 771323626)
Movie.create(title: "Byzantium", year: 2013, description: "BYZANTIUM is director Neil Jordan\'s (Interview with the Vampire, The Crying Game) sexy and stylish fantasy thriller about mother and daughter vampires dealing with the pitfalls of eternal life. Two mysterious women seek refuge in a run-down coastal resort. Clara (Gemma Arterton) meets lonely Noel (Daniel Mays), who provides shelter in his deserted guesthouse, Byzantium. Schoolgirl Eleanor (Saoirse Ronan, Hanna, Atonement) befriends Frank (Caleb Landry Jones) and tells him their lethal secret: They were born 200 years ago and survive on human blood. As knowledge of their secret spreads, their past catches up on them with deathly consequence. Also starring Sam Riley and Jonny Lee Miller. (c) IFC", rt_id: 771303874)

Critic.create!(critic: "Tom Huddleston", publication: "Time Out")
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/london/film/hyde-park-on-hudson")
Critic.create!(critic: "Connie Ogle", publication: "Miami Herald")
CriticOpinion.create!(like: "false", url: "http://www.miami.com/039hyde-park-hudson039-r-article")
Critic.create!(critic: "Tom Long", publication: "Detroit News")
CriticOpinion.create!(like: "false", url: "http://www.detroitnews.com/article/20121221/ENT02/212210321/1034/ent02/Review-Bill-Murray-dazzles-while-Hyde-Park-Hudson-wanders")
Critic.create!(critic: "Richard Roeper", publication: "Richard Roeper.com")
CriticOpinion.create!(like: "false", url: "http://www.richardroeper.com/reviews/h.aspx")
Critic.create!(critic: "Rick Groen", publication: "Globe and Mail")
CriticOpinion.create!(like: "true", url: "http://www.theglobeandmail.com/arts/film/film-reviews/hyde-park-on-hudson-presidential-history-as-cheery-shakespearean-revel/article6326019/")
Critic.create!(critic: "Ann Hornaday", publication: "Washington Post")
CriticOpinion.create!(like: "true", url: "http://www.washingtonpost.com/gog/movies/hyde-park-on-hudson,1224993/critic-review.html")
Critic.create!(critic: "Moira MacDonald", publication: "Seattle Times")
CriticOpinion.create!(like: "false", url: "http://seattletimes.com/html/movies/2019898650_moviehydexml.html")
Critic.create!(critic: "Peter Howell", publication: "Toronto Star")
CriticOpinion.create!(like: "false", url: "http://www.thestar.com/entertainment/movies/article/1301965--hyde-park-on-hudson-review-history-depleted")
Critic.create!(critic: "Mick LaSalle", publication: "San Francisco Chronicle")
CriticOpinion.create!(like: "false", url: "http://www.sfgate.com/movies/article/Hyde-Park-on-Hudson-review-Forget-real-FDR-4116153.php")
Critic.create!(critic: "Colin Covert", publication: "Minneapolis Star Tribune")
CriticOpinion.create!(like: "true", url: "http://www.startribune.com/entertainment/movies/183394171.html?refer=y")
Critic.create!(critic: "Mark Jenkins", publication: "NPR")
CriticOpinion.create!(like: "false", url: "http://www.npr.org/2013/02/07/171176637/a-sorcerer-a-white-snake-and-lots-of-cgi-magic?ft=1&f=1045")
Critic.create!(critic: "Simon Abrams", publication: "Village Voice")
CriticOpinion.create!(like: "false", url: "http://www.villagevoice.com/2013-02-06/film/the-sorcerer-and-the-white-snake/")
Critic.create!(critic: "Justin Chang", publication: "Variety")
CriticOpinion.create!(like: "false", url: "http://www.variety.com/review/VE1117945952/")
Critic.create!(critic: "Deborah Young", publication: "Hollywood Reporter")
CriticOpinion.create!(like: "true", url: "http://www.hollywoodreporter.com/review/sorcerer-white-snake-venice-film-230809")
Critic.create!(critic: "Joe Leydon", publication: "Variety")
CriticOpinion.create!(like: "true", url: "http://www.variety.com/review/VE1117948916?refcatid=31")
Critic.create!(critic: "Chris Vognar", publication: "Dallas Morning News")
CriticOpinion.create!(like: "false", url: "http://www.dallasnews.com/entertainment/movies/reviews/20121206-bad-kids-go-to-hell-plays-like-a-straight-to-dvd-bad-dream-c-.ece")
Critic.create!(critic: "Scott Foundas", publication: "Village Voice")
CriticOpinion.create!(like: "false", url: "http://www.villagevoice.com/2013-02-06/film/runaway-slaves-torment-the-haunting-in-connecticut-sequel-ghosts-of-georgia/")
Critic.create!(critic: "Nick Schager", publication: "Time Out New York")
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/us/film/the-haunting-in-connecticut-2-ghosts-of-georgia-movie-review")
Critic.create!(critic: "Frank Scheck", publication: "Hollywood Reporter")
CriticOpinion.create!(like: "true", url: "http://www.hollywoodreporter.com/movie/haunting-connecticut-2-ghosts-georgia/review/417436")
Critic.create!(critic: "Joe Leydon", publication: "Variety")
CriticOpinion.create!(like: "true", url: "http://www.variety.com/review/VE1117949144/")
Critic.create!(critic: "William Goss", publication: "Film.com")
CriticOpinion.create!(like: "false", url: "http://www.film.com/movies/review-the-haunting-in-connecticut-2-ghosts-of-georgia-is-frightfully-familiar")
Critic.create!(critic: "Mark Olsen", publication: "Los Angeles Times")
CriticOpinion.create!(like: "false", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-mn-haunting-in-connecticut-2-capsule-20130201,0,5020065.story")
Critic.create!(critic: "Tom Huddleston", publication: "Time Out")
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/film/reviews/91477/django-unchained.html")
Critic.create!(critic: "Lisa Kennedy", publication: "Denver Post")
CriticOpinion.create!(like: "true", url: "http://www.denverpost.com/entertainment/ci_22255932/movie-review-is-django-unchained-tarantinos-great-american")
Critic.create!(critic: "Anthony Lane", publication: "New Yorker")
CriticOpinion.create!(like: "false", url: "http://www.newyorker.com/arts/critics/cinema/2013/01/07/130107crci_cinema_lane")
Critic.create!(critic: "Glenn Kenny", publication: "MSN Movies")
CriticOpinion.create!(like: "false", url: "http://movies.msn.com/movies/movie-critic-reviews/django-unchained/")
Critic.create!(critic: "Joe Morgenstern", publication: "Wall Street Journal")
CriticOpinion.create!(like: "true", url: "http://online.wsj.com/article/SB10001424127887323984704578205371996961476.html")
Critic.create!(critic: "Andrew O'Hehir", publication: "Salon.com")
CriticOpinion.create!(like: "false", url: "http://www.salon.com/2012/12/26/tarantinos_incoherent_three_hour_bloodbath/")
Critic.create!(critic: "Rene Rodriguez", publication: "Miami Herald")
CriticOpinion.create!(like: "true", url: "http://www.miami.com/039django-unchained039-r-article")
Critic.create!(critic: "Ann Hornaday", publication: "Washington Post")
CriticOpinion.create!(like: "true", url: "http://www.washingtonpost.com/gog/movies/django-unchained,1209972/critic-review.html")
Critic.create!(critic: "Bill Goodykoontz", publication: "Arizona Republic")
CriticOpinion.create!(like: "true", url: "http://www.azcentral.com/thingstodo/movies/articles/20121220django-unchained-review-goodykoontz.html")
Critic.create!(critic: "Tom Long", publication: "Detroit News")
CriticOpinion.create!(like: "true", url: "http://www.detroitnews.com/article/20121225/ENT02/212250302/1034")
Critic.create!(critic: "Robert Abele", publication: "Los Angeles Times")
CriticOpinion.create!(like: "true", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-mn-dragon-capsule-20121130,0,7730925.story")
Critic.create!(critic: "Farran Smith Nehme", publication: "New York Post")
CriticOpinion.create!(like: "true", url: "http://www.nypost.com/p/entertainment/movies/dragon_sxbWYsok3Z4w45YU38DOBN")
Critic.create!(critic: "A.O. Scott", publication: "New York Times")
CriticOpinion.create!(like: "false", url: "http://movies.nytimes.com/2012/11/30/movies/dragon-wu-xia-directed-by-peter-ho-sun-chan.html?smid=tw-nytimesmovies&seid=auto")
Critic.create!(critic: "Mark Jenkins", publication: "NPR")
CriticOpinion.create!(like: "true", url: "http://www.npr.org/2012/11/29/165683695/from-a-rom-com-director-a-subtle-kung-fu-flick?ft=1&f=1045")
Critic.create!(critic: "Joe Neumaier", publication: "New York Daily News")
CriticOpinion.create!(like: "false", url: "http://www.nydailynews.com/entertainment/tv-movies/movie-reviews-gatekeepers-otelo-burning-dragon-article-1.1210412")
Critic.create!(critic: "Mary Corliss", publication: "TIME Magazine")
CriticOpinion.create!(like: "true", url: "http://entertainment.time.com/2012/11/29/dragon-the-one-armed-swordsman-with-a-heart/")
Critic.create!(critic: "Bill Goodykoontz", publication: "Arizona Republic")
CriticOpinion.create!(like: "true", url: "http://www.azcentral.com/thingstodo/movies/articles/20121128dragon-movie-review-goodykoontz.html")
Critic.create!(critic: "Nick Pinkerton", publication: "Village Voice")
CriticOpinion.create!(like: "true", url: "http://www.villagevoice.com/2012-11-28/film/dragon-wu-xia-film-review/")
Critic.create!(critic: "Keith Uhlich", publication: "Time Out New York")
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/us/film/dragon")
Critic.create!(critic: "Derek Adams", publication: "Time Out")
CriticOpinion.create!(like: "true", url: "http://www.timeout.com/film/reviews/91921/a-monster-in-paris.html")
Critic.create!(critic: "Sheri Linden", publication: "Los Angeles Times")
CriticOpinion.create!(like: "false", url: "http://www.latimes.com/entertainment/movies/moviesnow/la-et-mn-save-the-date-capsule-20121214,0,6808548.story")
Critic.create!(critic: "Sara Stewart", publication: "New York Post")
CriticOpinion.create!(like: "false", url: "http://www.nypost.com/p/entertainment/movies/leave_this_flick_at_the_altar_MhhEabOprKeFZzS5SeSKMI")
Critic.create!(critic: "Rachel Saltz", publication: "New York Times")
CriticOpinion.create!(like: "false", url: "http://movies.nytimes.com/2012/12/14/movies/save-the-date-directed-by-michael-mohan.html?partner=rss&emc=rss")
Critic.create!(critic: "Ella Taylor", publication: "NPR")
CriticOpinion.create!(like: "false", url: "http://www.npr.org/2012/12/13/166681799/save-the-date-something-borrowed-not-much-new?ft=1&f=1045")
Critic.create!(critic: "Mary F. Pols", publication: "TIME Magazine")
CriticOpinion.create!(like: "false", url: "http://entertainment.time.com/2012/12/13/save-the-date-movie-review-everyone-loves-lizzy-caplan/")
Critic.create!(critic: "Elizabeth Weitzman", publication: "New York Daily News")
CriticOpinion.create!(like: "true", url: "http://www.nydailynews.com/entertainment/tv-movies/movie-reviews-save-date-fury-hour-article-1.1219473")
Critic.create!(critic: "Sam Adams", publication: "Time Out New York")
CriticOpinion.create!(like: "false", url: "http://www.timeout.com/us/film/save-the-date")
Critic.create!(critic: "Melissa Anderson", publication: "Village Voice")
CriticOpinion.create!(like: "false", url: "http://www.villagevoice.com/2012-12-12/film/save-the-date-film-review/")
Critic.create!(critic: "Lisa Schwarzbaum", publication: "Entertainment Weekly")
CriticOpinion.create!(like: "false", url: "http://www.ew.com/ew/article/0,,20653676,00.html")
Critic.create!(critic: "John Anderson", publication: "Variety")
CriticOpinion.create!(like: "false", url: "http://www.variety.com/review/VE1117946945.html?categoryid=31&cs=1")
Critic.create!(critic: "Russell Edwards", publication: "Variety")
CriticOpinion.create!(like: "false", url: "http://www.variety.com/review/VE1117947698.html?categoryid=31&cs=1")
Critic.create!(critic: "Tom Charity", publication: "CNN.com")
CriticOpinion.create!(like: "false", url: "http://www.cnn.com/2013/01/11/showbiz/movies/gangster-squad-review-charity/index.html?iref=allsearch")
Critic.create!(critic: "Anthony Lane", publication: "New Yorker")
CriticOpinion.create!(like: "false", url: "http://www.newyorker.com/arts/reviews/film/gangster_squad_fleischer")
Critic.create!(critic: "Ricardo Baca", publication: "Denver Post")
CriticOpinion.create!(like: "true", url: "http://www.denverpost.com/movies/ci_22341778/movie-review-sean-penn-steals-this-shoot-em")
Critic.create!(critic: "Peter Rainer", publication: "Christian Science Monitor")
CriticOpinion.create!(like: "false", url: "http://www.csmonitor.com/The-Culture/Movies/2013/0111/Sean-Penn-plays-a-mobster-with-twisted-relish-in-Gangster-Squad?nav=397-csm_subcategory-leadStory")
Critic.create!(critic: "Richard Roeper", publication: "Richard Roeper.com")
CriticOpinion.create!(like: "true", url: "http://www.richardroeper.com/reviews/gangstersquad.aspx")
Critic.create!(critic: "Colin Covert", publication: "Minneapolis Star Tribune")
CriticOpinion.create!(like: "false", url: "http://www.startribune.com/entertainment/movies/186350422.html?refer=y")
Critic.create!(critic: "Rick Groen", publication: "Globe and Mail")
CriticOpinion.create!(like: "false", url: "http://www.theglobeandmail.com/arts/film/film-reviews/gangster-squad-just-guys-and-dolls-playing-dress-up/article7178203/")
Critic.create!(critic: "Stephen Whitty", publication: "Newark Star-Ledger")
CriticOpinion.create!(like: "false", url: "http://www.nj.com/entertainment/index.ssf/2013/01/gangster_squad_review_gosling.html")
Critic.create!(critic: "Adam Graham", publication: "Detroit News")
CriticOpinion.create!(like: "false", url: "http://www.detroitnews.com/article/20130111/ENT02/301110315/1034/ent02/Review-Gangster-Squad-s-all-star-cast-doesn-t-enough-character-get-job-done")
Critic.create!(critic: "Lou Lumenick", publication: "New York Post")
CriticOpinion.create!(like: "false", url: "http://www.nypost.com/p/entertainment/movies/flaw_order_kBXWJ6a984iskWCNSAUu4H")